[phases.setup]
nixPkgs = ["nodejs_20", "python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "node --version",
  "python3 --version",
  "python3 -m pip --version",
  "npm install",
  "python3 -m pip install -v -r requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
